apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    component: apache
  name: apachehome
spec:
  triggers:
  - type: ConfigChange
  replicas: 1
  selector:
    app: apachehome
    component: apache
  template:
    metadata:
      labels:
        app: apachehome
        component: apache
    spec:
      volumes: 
        - name: apache-data
          persistentVolumeClaim:
            claimName: apachehome
      containers:
      - image: 'hub.qiyunxin.com/qiyunxin/apache:latest'
        name: apache
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
        volumeMounts:
          - name: apache-data
            mountPath: /var/www/html
        imagePullPolicy: IfNotPresent
